// Code generated by protoc-json-shim. DO NOT EDIT.
package hcpv1

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for Link
func (this *Link) MarshalJSON() ([]byte, error) {
	str, err := CloudlinkMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Link
func (this *Link) UnmarshalJSON(b []byte) error {
	return CloudlinkUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for LinkConfig
func (this *LinkConfig) MarshalJSON() ([]byte, error) {
	str, err := CloudlinkMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LinkConfig
func (this *LinkConfig) UnmarshalJSON(b []byte) error {
	return CloudlinkUnmarshaler.Unmarshal(b, this)
}

var (
	CloudlinkMarshaler   = &protojson.MarshalOptions{}
	CloudlinkUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
